name: Mise a jour BRVM Aliou
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install requests pandas
      - run: python update_data.py
      - run: |
          git config --global user.name 'Aliou-Bot'
          git config --global user.email 'bot@github.com'
          git add data.json
          git commit -m "MAJ" || exit 0
          git push
